
import AuthTemplate from "@/app/components/templates/AuthTemplate";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AuthTemplate>{children}</AuthTemplate>;
}