import type { Metadata } from "next";
import { Oswald, Roboto_Mono } from "next/font/google";
import "./globals.css";
import AppProvider from "@/app/components/providers/AppProvider";

const oswald  = Oswald({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${robotoMono.variable}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
