import { CORE_CHECK_REFRESH_TOKEN_ENDPOINT, CORE_LOGIN_ENDPOINT, CORE_REGISTER_ENDPOINT, CORE_VERIFY_ENDPOINT } from "./coreApi";

export const API_NOT_TOKEN = 
[
  `/${CORE_LOGIN_ENDPOINT}`, 
  `/${CORE_CHECK_REFRESH_TOKEN_ENDPOINT}`,
  `/${CORE_REGISTER_ENDPOINT}`,
  `/${CORE_VERIFY_ENDPOINT}`
];